django_test:
  build: .
  command: "sh deploy.sh"
  environment:
    RUN_ENV: "TEST"
    RABBITMQ_DEFAULT_USER: "$RABBITMQ_DEFAULT_USER"
    RABBITMQ_DEFAULT_PASS: "$RABBITMQ_DEFAULT_PASS"
  ports:
   - "80:8001"
  volumes:
   - .:/project
  links:
   - redis_test
   - postgres_test
redis_test:
  image: redis:latest
  command: redis-server --appendonly yes
postgres_test:
  image: postgres:9.4
  volumes:
    - test_postgres_9_4:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
    POSTGRES_PASSWORD: "scheduling_test"
    POSTGRES_USER: "scheduling_test"